/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Quiz;

import javax.swing.JOptionPane;

/**
 *
 * @author 2407982
 */
public class EasyScienceQuiz extends javax.swing.JFrame {

    /**
     * Creates new form EasyScienceQuiz
     */
    public EasyScienceQuiz() {
        initComponents();
        QuizUtilities.setTimer(timerLabel, feedbackLabel, submitButton, nextButton);
        loadQuestion(ques, "Au", "Ag", "Fe", "Ni");
    }
    
    private void loadQuestion(String questionText, String opt1, String opt2, String opt3, String opt4) 
    {
        buttonGroup.clearSelection();
        ques = questionText;        
        questionLabel.setText(String.format("""
        <html><body style='width: 450px'>Question %d: %s</body></html>
        """,
        currentQuestion, ques));
        answer_one.setText(opt1);
        answer_two.setText(opt2);
        answer_three.setText(opt3);
        answer_four.setText(opt4);
        submitButton.setEnabled(true);
        nextButton.setEnabled(false);
        feedbackLabel.setText("");
        QuizUtilities.timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        background = new javax.swing.JPanel();
        innerBackground = new javax.swing.JPanel();
        questionLabel = new javax.swing.JLabel();
        answer_one = new javax.swing.JRadioButton();
        answer_two = new javax.swing.JRadioButton();
        answer_three = new javax.swing.JRadioButton();
        answer_four = new javax.swing.JRadioButton();
        submitButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        scoreLabel = new javax.swing.JLabel();
        feedbackLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        timerLabel = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        restartButton = new javax.swing.JButton();
        soundToggle = new javax.swing.JToggleButton();
        text_three = new javax.swing.JLabel();

        buttonGroup.add(answer_one);
        buttonGroup.add(answer_two);
        buttonGroup.add(answer_three);
        buttonGroup.add(answer_four);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 140, 0));

        innerBackground.setBackground(new java.awt.Color(255, 218, 185));
        innerBackground.setPreferredSize(new java.awt.Dimension(612, 510));

        questionLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        questionLabel.setForeground(new java.awt.Color(25, 25, 112));

        answer_one.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        answer_one.setForeground(new java.awt.Color(25, 25, 112));
        answer_one.setText("Au");
        answer_one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer_oneActionPerformed(evt);
            }
        });

        answer_two.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        answer_two.setForeground(new java.awt.Color(25, 25, 112));
        answer_two.setText("Ag");
        answer_two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer_twoActionPerformed(evt);
            }
        });

        answer_three.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        answer_three.setForeground(new java.awt.Color(25, 25, 112));
        answer_three.setText("Fe");

        answer_four.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        answer_four.setForeground(new java.awt.Color(25, 25, 112));
        answer_four.setText("Ni");
        answer_four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer_fourActionPerformed(evt);
            }
        });

        submitButton.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        submitButton.setForeground(new java.awt.Color(25, 25, 112));
        submitButton.setText("Submit Answer");
        submitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                submitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                submitButtonMouseExited(evt);
            }
        });
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        nextButton.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        nextButton.setForeground(new java.awt.Color(25, 25, 112));
        nextButton.setText("Next Question");
        nextButton.setEnabled(false);
        nextButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nextButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nextButtonMouseExited(evt);
            }
        });
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        scoreLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        scoreLabel.setForeground(new java.awt.Color(25, 25, 112));
        scoreLabel.setText("Score: 0 / 5");

        feedbackLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        feedbackLabel.setForeground(new java.awt.Color(25, 25, 112));

        progressBar.setBackground(new java.awt.Color(106, 50, 159));
        progressBar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        progressBar.setForeground(new java.awt.Color(106, 50, 159));

        timerLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        timerLabel.setForeground(new java.awt.Color(25, 25, 112));
        timerLabel.setText("Timer: 04:59");

        javax.swing.GroupLayout innerBackgroundLayout = new javax.swing.GroupLayout(innerBackground);
        innerBackground.setLayout(innerBackgroundLayout);
        innerBackgroundLayout.setHorizontalGroup(
            innerBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innerBackgroundLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(innerBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(innerBackgroundLayout.createSequentialGroup()
                        .addComponent(feedbackLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(innerBackgroundLayout.createSequentialGroup()
                        .addGroup(innerBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(questionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(innerBackgroundLayout.createSequentialGroup()
                                .addGroup(innerBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(innerBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(innerBackgroundLayout.createSequentialGroup()
                                            .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(38, 38, 38)
                                            .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(answer_one, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(answer_two, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(answer_three, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(answer_four, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE))
                                    .addGroup(innerBackgroundLayout.createSequentialGroup()
                                        .addComponent(scoreLabel)
                                        .addGap(76, 76, 76)
                                        .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(64, 64, 64)
                                        .addComponent(timerLabel)))
                                .addGap(0, 75, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        innerBackgroundLayout.setVerticalGroup(
            innerBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innerBackgroundLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(innerBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scoreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(questionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(answer_one)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer_two)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer_three)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(answer_four)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(feedbackLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(innerBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        exitButton.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        exitButton.setForeground(new java.awt.Color(25, 25, 112));
        exitButton.setText("Exit");
        exitButton.addActionListener(e -> QuizUtilities.exitApp());
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitButtonMouseExited(evt);
            }
        });

        restartButton.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        restartButton.setForeground(new java.awt.Color(25, 25, 112));
        restartButton.setText("Restart");
        restartButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                restartButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                restartButtonMouseExited(evt);
            }
        });
        restartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartButtonActionPerformed(evt);
            }
        });

        soundToggle.setBackground(new java.awt.Color(255, 140, 0));
        soundToggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Quiz/assets/sound_icon.png"))); // NOI18N
        soundToggle.setBorder(null);
        soundToggle.setBorderPainted(false);

        text_three.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        text_three.setForeground(new java.awt.Color(25, 25, 112));
        text_three.setText("Created by Oyinkansola");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(soundToggle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(innerBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(restartButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addGap(0, 771, Short.MAX_VALUE)
                .addComponent(text_three, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(soundToggle)
                        .addGap(10, 10, 10)
                        .addComponent(innerBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(restartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(text_three, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        soundToggle.addActionListener(e -> QuizUtilities.toggleSound(soundToggle));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void answer_oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer_oneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer_oneActionPerformed

    private void answer_twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer_twoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer_twoActionPerformed

    private void answer_fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer_fourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer_fourActionPerformed

    private void submitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitButtonMouseEntered
        // TODO add your handling code here:
        QuizUtilities.setButtonMouseEntered(submitButton);
    }//GEN-LAST:event_submitButtonMouseEntered

    private void submitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitButtonMouseExited
        // TODO add your handling code here:
        QuizUtilities.setButtonMouseExited(submitButton);
    }//GEN-LAST:event_submitButtonMouseExited

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        boolean isCorrect = false;
        switch (currentQuestion) {
            case 1:
            if (answer_one.isSelected()) {
                isCorrect = true;
            }
            break;
            case 2:
            if (answer_two.isSelected()) {
                isCorrect = true;
            }
            break;
            case 3:
            if (answer_three.isSelected()) {
                isCorrect = true;
            }
            break;
            case 4:
            if (answer_three.isSelected()) {
                isCorrect = true;
            }
            break;
            case 5:
            if (answer_two.isSelected()) {
                isCorrect = true;
            }
            break;
            default:
            JOptionPane.showMessageDialog(this, "Invalid question number.");
            return;
        }

        if(answer_one.isSelected() || answer_two.isSelected() || answer_three.isSelected() || answer_four.isSelected()) {
            currentQuestion++;
            submitButton.setEnabled(false);
            nextButton.setEnabled(true);
            if(isCorrect) {
                score++;
                QuizUtilities.scoreHistory.add(1);
                scoreLabel.setText("Score: " + score + " / 5");

                feedbackLabel.setText("Your answer is correct. Click on the next button to proceed.");

            }
            else{
                feedbackLabel.setText("Your answer is not correct. Click on the next button to proceed.");
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Please select one option from the answers given.");
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void nextButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonMouseEntered
        // TODO add your handling code here:
        QuizUtilities.setButtonMouseEntered(nextButton);
    }//GEN-LAST:event_nextButtonMouseEntered

    private void nextButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonMouseExited
        // TODO add your handling code here:
        QuizUtilities.setButtonMouseExited(nextButton);
    }//GEN-LAST:event_nextButtonMouseExited

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        switch (currentQuestion) {
            case 2:
            loadQuestion("Which planet is known as the 'Red planet'?"
                , "Venus", "Mars", "Jupiter", "Saturn");
            break;
            case 3:
            loadQuestion("What is the powerhouse of the cell?",
                "Nucleus", "Ribosome", "Mitochondria", "Chloroplast");
            break;
            case 4:
            loadQuestion("What is the unit of electric current?"
               , "Volt", "Watt","Ampere","Ohm");
            break;
            case 5:
            loadQuestion("Which part of the human brain controls "
                + "balance and coordination? ", "Cerebrum", "Cerebellum"
                ,"Medulla", "Hypothalamus");
            break;
            case 6:
            feedbackLabel.setVisible(false);
            submitButton.setVisible(false);
            nextButton.setText("Next Quiz");
            nextButton.setEnabled(true);
            answer_one.setVisible(false);
            answer_two.setVisible(false);
            answer_three.setVisible(false);
            answer_four.setVisible(false);
            timerLabel.setVisible(false);
            questionLabel.setText("Move to the next quiz (Computing) by clicking on Next button");
            QuizUtilities.timer.stop();
            innerBackground.setLayout(null);
            scoreLabel.setFont(new java.awt.Font("Comic Sans MS", java.awt.Font.BOLD, 40));
            scoreLabel.setText("Final Score: " + score + " / 5");
            scoreLabel.setBounds(130, 100, 500, 100);
            progressBar.setBounds(150, 200, 300, 60);
            questionLabel.setBounds(60, 270, 590, 60);
            nextButton.setBounds(210, 335, 176, 64);
            currentQuestion++;
            break;
            default:
            new EasyComputerQuiz().setVisible(true);
            this.dispose();
            break;
        }
        int progress = (currentQuestion * 100) / 6;
        progressBar.setValue(progress);
        progressBar.setStringPainted(true);
    }//GEN-LAST:event_nextButtonActionPerformed

    private void exitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseEntered
        // TODO add your handling code here:
        QuizUtilities.setButtonMouseEntered(exitButton);
    }//GEN-LAST:event_exitButtonMouseEntered

    private void exitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseExited
        // TODO add your handling code here:
        QuizUtilities.setButtonMouseExited(exitButton);
    }//GEN-LAST:event_exitButtonMouseExited

    private void restartButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restartButtonMouseEntered
        // TODO add your handling code here:
        QuizUtilities.setButtonMouseEntered(restartButton);
    }//GEN-LAST:event_restartButtonMouseEntered

    private void restartButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restartButtonMouseExited
        // TODO add your handling code here:
        QuizUtilities.setButtonMouseExited(restartButton);
    }//GEN-LAST:event_restartButtonMouseExited

    private void restartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartButtonActionPerformed
        // TODO add your handling code here:
        new QuizGame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_restartButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EasyScienceQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EasyScienceQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EasyScienceQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EasyScienceQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EasyScienceQuiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton answer_four;
    private javax.swing.JRadioButton answer_one;
    private javax.swing.JRadioButton answer_three;
    private javax.swing.JRadioButton answer_two;
    private javax.swing.JPanel background;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel feedbackLabel;
    private javax.swing.JPanel innerBackground;
    private javax.swing.JButton nextButton;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel questionLabel;
    private javax.swing.JButton restartButton;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JToggleButton soundToggle;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel text_three;
    private javax.swing.JLabel timerLabel;
    // End of variables declaration//GEN-END:variables
    private int score = 0;
    private int currentQuestion = 1;
    private String question;
    private String ques = "What is the chemical symbol for gold?";
}
