/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Quiz;

import javax.swing.JOptionPane;


/**
 *
 * @author 2407982
 */
public class QuizGame extends javax.swing.JFrame {

    
    /**
     * Creates new form QuizGame
     */
    public QuizGame() {
        initComponents();
        QuizUtilities.scoreHistory.clear();
        QuizUtilities.loadMusic("src/Quiz/assets/medicine.wav");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        backgroundColor = new javax.swing.JPanel();
        exitButton = new javax.swing.JButton();
        startButton = new javax.swing.JButton();
        difficultLevel = new javax.swing.JRadioButton();
        easyLevel = new javax.swing.JRadioButton();
        selectTitle = new javax.swing.JLabel();
        backgroundImage = new javax.swing.JLabel();
        text_one = new javax.swing.JLabel();
        text_two = new javax.swing.JLabel();
        text_three = new javax.swing.JLabel();
        soundToggle = new javax.swing.JToggleButton();

        buttonGroup.add(easyLevel);
        buttonGroup.add(difficultLevel);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundColor.setBackground(new java.awt.Color(255, 140, 0));
        backgroundColor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitButton.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        exitButton.setForeground(new java.awt.Color(25, 25, 112));
        exitButton.setText("Exit");
        exitButton.setAlignmentX(1.0F);
        exitButton.setBorderPainted(false);
        exitButton.setFocusPainted(false);
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitButtonMouseExited(evt);
            }
        });
        exitButton.addActionListener(e -> QuizUtilities.exitApp());
        backgroundColor.add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 300, 90, 50));

        startButton.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        startButton.setForeground(new java.awt.Color(25, 25, 112));
        startButton.setText("Start Quiz");
        startButton.setAlignmentX(1.0F);
        startButton.setBorderPainted(false);
        startButton.setFocusPainted(false);
        startButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                startButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                startButtonMouseExited(evt);
            }
        });
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        backgroundColor.add(startButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 490, 140, 50));

        difficultLevel.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        difficultLevel.setText("Difficult");
        backgroundColor.add(difficultLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, -1, -1));

        easyLevel.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        easyLevel.setText("Easy");
        easyLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyLevelActionPerformed(evt);
            }
        });
        backgroundColor.add(easyLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, -1, -1));

        selectTitle.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        selectTitle.setText("Select Level:");
        backgroundColor.add(selectTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, -1, -1));

        backgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Quiz/assets/background image.jpg"))); // NOI18N
        backgroundColor.add(backgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        text_one.setFont(new java.awt.Font("Comic Sans MS", 1, 22)); // NOI18N
        text_one.setForeground(new java.awt.Color(25, 25, 112));
        text_one.setText("Think Fast. Play Smart.");
        backgroundColor.add(text_one, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 580, -1, -1));

        text_two.setFont(new java.awt.Font("Comic Sans MS", 1, 15)); // NOI18N
        text_two.setForeground(new java.awt.Color(25, 25, 112));
        text_two.setText("Click on Start Quiz to begin your quiz journey.");
        backgroundColor.add(text_two, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 611, -1, 30));

        text_three.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        text_three.setForeground(new java.awt.Color(25, 25, 112));
        text_three.setText("Created by Oyinkansola");
        backgroundColor.add(text_three, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 660, 140, 20));

        soundToggle.setBackground(new java.awt.Color(255, 140, 0));
        soundToggle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Quiz/assets/sound_icon.png"))); // NOI18N
        soundToggle.setBorder(null);
        soundToggle.setBorderPainted(false);
        backgroundColor.add(soundToggle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        soundToggle.addActionListener(e -> QuizUtilities.toggleSound(soundToggle));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backgroundColor, javax.swing.GroupLayout.PREFERRED_SIZE, 911, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
        if(easyLevel.isSelected()) {
           new EasyEnglishQuiz().setVisible(true); 
           this.dispose();
        }
        else if (difficultLevel.isSelected()) {
            new DifficultEnglishQuiz().setVisible(true);
            this.dispose();
        }
        else {
            JOptionPane.showMessageDialog(this, "Please select the game difficulty level.");
        }      
    }//GEN-LAST:event_startButtonActionPerformed

    private void startButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startButtonMouseEntered
        // TODO add your handling code here:      
        QuizUtilities.setButtonMouseEntered(startButton);
    }//GEN-LAST:event_startButtonMouseEntered

    private void startButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startButtonMouseExited
        // TODO add your handling code here:
        QuizUtilities.setButtonMouseExited(startButton);
    }//GEN-LAST:event_startButtonMouseExited

    private void exitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseExited
        QuizUtilities.setButtonMouseExited(exitButton);
    }//GEN-LAST:event_exitButtonMouseExited

    private void exitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseEntered
        QuizUtilities.setButtonMouseEntered(exitButton);
    }//GEN-LAST:event_exitButtonMouseEntered

    private void easyLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_easyLevelActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuizGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuizGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuizGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuizGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuizGame().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundColor;
    private javax.swing.JLabel backgroundImage;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JRadioButton difficultLevel;
    private javax.swing.JRadioButton easyLevel;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel selectTitle;
    private javax.swing.JToggleButton soundToggle;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel text_one;
    private javax.swing.JLabel text_three;
    private javax.swing.JLabel text_two;
    // End of variables declaration//GEN-END:variables
}